version: '2.0'
services:
  web:
    build: .
    ports:
      - 2710:2710
    depends_on:
      - db
    env_file:
      - docker-compose.env
  db:
    image: healthcheck/mariadb:latest
    env_file:
      - docker-compose.env
